global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@block-watcher.local'
  smtp_auth_username: ''
  smtp_auth_password: ''

# Templates for alert notifications
templates:
  - '/etc/alertmanager/*.tmpl'

# Routing tree for alerts
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  # Critical alerts - immediate notification
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 5s
    repeat_interval: 5m
  
  # Warning alerts - less frequent notifications
  - match:
      severity: warning
    receiver: 'warning-alerts'
    group_wait: 30s
    repeat_interval: 30m

  # Database specific alerts
  - match:
      service: postgresql
    receiver: 'database-alerts'
    
  # Block Watcher application alerts  
  - match:
      service: block-watcher
    receiver: 'application-alerts'

# Alert receivers/notification channels
receivers:
- name: 'default-receiver'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alert'
        password: 'webhook'

- name: 'critical-alerts'
  # Console logging for development
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook/critical'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'alert'
        password: 'webhook'
  
  # Example Slack integration (uncomment and configure)
  # slack_configs:
  # - api_url: 'YOUR_SLACK_WEBHOOK_URL'
  #   channel: '#alerts-critical'
  #   title: 'CRITICAL: Block Watcher Alert'
  #   text: |
  #     {{ range .Alerts }}
  #     🚨 *{{ .Annotations.summary }}*
  #     {{ .Annotations.description }}
  #     *Service:* {{ .Labels.service }}
  #     *Severity:* {{ .Labels.severity }}
  #     {{ end }}

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook/warning'
    send_resolved: true
    
  # Example email notifications (configure SMTP settings above)
  # email_configs:
  # - to: 'devops@yourcompany.com'
  #   subject: 'Block Watcher Warning: {{ .GroupLabels.alertname }}'
  #   html: |
  #     <h2>Block Watcher Warning Alert</h2>
  #     {{ range .Alerts }}
  #     <p><strong>{{ .Annotations.summary }}</strong></p>
  #     <p>{{ .Annotations.description }}</p>
  #     <p>Service: {{ .Labels.service }}, Severity: {{ .Labels.severity }}</p>
  #     {{ end }}

- name: 'database-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook/database'
    send_resolved: true

- name: 'application-alerts'
  webhook_configs:
  - url: 'http://host.docker.internal:8000/webhook/application'
    send_resolved: true

# Inhibition rules - suppress certain alerts when others are firing
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']

# Silence specific alerts during maintenance windows
# silences: []
