apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: block-watcher-alerts
  namespace: observability
  labels:
    app: block-watcher
    release: observability
spec:
  groups:
  - name: block-watcher
    rules:
    - alert: BlockWatcherDown
      expr: up{service="block-watcher-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Block Watcher application is down"
        description: "Block Watcher has been down for more than 1 minute"

    - alert: BlockWatcherHighErrorRate
      expr: rate(http_server_requests_seconds_count{status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate in Block Watcher"
        description: "Block Watcher error rate is {{ $value }} errors per second"

    - alert: BlockWatcherHighLatency
      expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 0.5
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High latency in Block Watcher"
        description: "Block Watcher 95th percentile latency is {{ $value }}s"

    - alert: BlockWatcherDatabaseDown
      expr: up{job="postgres"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Block Watcher database is down"
        description: "PostgreSQL database is not responding"
