apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: block-watcher-service-monitor
  namespace: observability
  labels:
    app: block-watcher
    release: observability
spec:
  namespaceSelector:
    matchNames:
    - block-watcher
  selector:
    matchLabels:
      app: block-watcher
  endpoints:
  - port: http
    path: /api/metrics
    interval: 15s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: instance