global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'local-dev'
    environment: 'development'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Block Watcher NestJS Application
  - job_name: 'block-watcher'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /api/metrics
    static_configs:
      - targets: ['host.docker.internal:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'block-watcher-app'
    honor_labels: false

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter - Host system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # PostgreSQL Database metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Blackbox Exporter - HTTP endpoint monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://host.docker.internal:3000/api/health
        - http://host.docker.internal:3000/api/health/liveness  
        - http://host.docker.internal:3000/api/health/readiness
        - http://host.docker.internal:3000/api/health/database
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Grafana  
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
